import type { NextPage } from 'next';
import Head from 'next/head';

const Test: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="section-padding-primary">
        <div className="container">
          <div className="bg-primaryGradient rounded-lg p-[20px] lg:p-[40px] text-center">
            <h1 className="text-white text-[1.875rem] lg:text-[3rem] font-medium lg:font-bold">
              Welcome to BrightonSEO
            </h1>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Test;
